---
printWidth: 100
tabWidth: 4
useTabs: true
trailingComma: all
semi: true
singleQuote: false

overrides:
    - files: "*.md"
      options:
          useTabs: false
    - files: "*.svelte"
      options:
          parser: "svelte"

plugins:
    - ./node_modules/prettier-plugin-svelte
    - ./node_modules/prettier-plugin-tailwindcss
    - ./node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js
pluginSearchDirs: false

importOrder:
    - "^node:"
    - "^[^@.]"
    - "^@"
    - "^\\."
